import { afterEach, describe, expect, it, vi } from 'vitest';
import { analyzeCardImage, matchCatalog, type ScanAnalysis } from '@/lib/vision';
afterEach(() => vi.unstubAllGlobals());
const analysis: ScanAnalysis = { identified: true, name: 'Charizard', setName: 'Base Set', number: '4/102', rarity: 'Holo Rare', holo: true, year: '1999', verdict: 'suspect', confidence: 90, signals: [], summary: 'Visible text matches', matchedCardId: null };
describe('photo identification safeguards', () => {
  it('requires exact set and collector number in local matching', () => { expect(matchCatalog(analysis).matchedCardId).toBe('charizard-base'); expect(matchCatalog({ ...analysis, setName: 'Base Set 2' }).matchedCardId).toBeNull(); expect(matchCatalog({ ...analysis, number: 'TG04' }).matchedCardId).toBeNull(); });
  it('explicitly rejects token-truncated responses', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response(JSON.stringify({ choices: [{ finish_reason: 'length', message: { content: '{"name":' } }] })))); await expect(analyzeCardImage('data:image/jpeg;base64,test')).rejects.toThrow('cut short'); });
  it('uses bounded reasoning and structured output without authenticating the specimen', async () => { const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ choices: [{ finish_reason: 'stop', message: { content: JSON.stringify({ ...analysis, set: 'Base Set', verdict: 'authentic' }) } }] }))); vi.stubGlobal('fetch', fetcher); const result = await analyzeCardImage('data:image/jpeg;base64,test'); expect(result.verdict).toBe('suspect'); const body = JSON.parse(fetcher.mock.calls[0][1].body); expect(body.max_tokens).toBeGreaterThan(2000); expect(body.reasoning.max_tokens).toBe(512); expect(body.response_format.type).toBe('json_schema'); });
  it('does not swallow service failures as counterfeit results', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('', { status: 503 }))); await expect(analyzeCardImage('data:image/jpeg;base64,test')).rejects.toThrow('service could not complete'); });
  it('passes cancellation to the request', async () => { const fetcher = vi.fn().mockRejectedValue(new DOMException('Cancelled', 'AbortError')); vi.stubGlobal('fetch', fetcher); const controller = new AbortController(); controller.abort(); await expect(analyzeCardImage('data:image/jpeg;base64,test', controller.signal)).rejects.toThrow(); expect(fetcher.mock.calls[0][1].signal.aborted).toBe(true); });
});
