import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery } from '@tanstack/react-query';
import { ShieldCheck, LockKeyhole, Database, ClipboardCheck } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/lib/auth';
import { useVca, type InspectionNote } from '@/lib/store';
import { supabase } from '@/lib/supabase';
import { CATALOG } from '@/lib/data';
import type { CatalogCard, GradeLabel, SubmissionStatus } from '@/lib/types';
import { Button } from '@/components/ui/button';
import PhotoInspection from '@/components/PhotoInspection';
const nextStatus: Partial<Record<SubmissionStatus, SubmissionStatus>> = { SUBMITTED: 'RECEIVED', RECEIVED: 'INSPECTING', INSPECTING: 'GRADING', GRADING: 'GRADED', GRADED: 'SHIPPED' };
export default function AdminOS() {
  const { session, isAdmin } = useAuth();
  const { submissions, submissionsError, updateSubmissionStatus, certifySubmission, adminPending } = useVca();
  const [tab, setTab] = useState<'queue' | 'catalog' | 'system'>('queue');
  const [selected, setSelected] = useState<string | null>(null);
  const [note, setNote] = useState<string>('');
  const [grade, setGrade] = useState<GradeLabel>('VCA 9');
  const [query, setQuery] = useState<string>('');
  const evidence = useQuery({ queryKey: ['submission-evidence', selected, session?.user.id], enabled: Boolean(isAdmin && selected), queryFn: async () => { const { data, error } = await supabase!.from('vca_submissions').select('details').eq('id', selected!).single(); if (error) throw new Error('Could not load submitted photos.'); return data.details as { inspection?: InspectionNote; cardName: string; cardSet: string; cardArt: string }; } });
  const saveEvidence = useMutation({ mutationFn: async (value: InspectionNote) => { const { error } = await supabase!.rpc('vca_record_inspection', { submission: selected, inspection: value }); if (error) throw new Error('Inspection evidence was not saved. Check permissions and status.'); }, onSuccess: () => evidence.refetch() });
  if (!isAdmin) return <div className="glass mx-auto max-w-lg space-y-5 rounded-3xl p-8"><LockKeyhole className="h-9 w-9 text-primary"/><h1 className="font-display text-2xl font-bold">Administrator access</h1><p className="text-sm leading-relaxed text-muted-foreground">{session ? 'Your account does not have a verified administrator role. Access must be assigned by the project owner; browser settings cannot grant it.' : 'Sign in with an administrator account. The old demo password no longer grants access.'}</p><Button asChild><Link to="/account">Account & sign in</Link></Button></div>;
  const sub = submissions.find(s => s.id === selected);
  const card: CatalogCard | undefined = sub ? { ...(CATALOG[0]), id: sub.cardId, name: sub.cardName, set: sub.cardSet, artUrl: sub.cardArt, number: '', variant: 'Submitted specimen' } : undefined;
  return <div className="space-y-5"><header><p className="eyebrow flex items-center gap-2"><ShieldCheck className="h-4 w-4"/>VERIFIED ADMINISTRATOR</p><h1 className="mt-2 font-display text-3xl font-bold">VCA operations</h1><p className="mt-2 text-sm text-muted-foreground">Account-owned intake. Recorded evidence. Audited grading decisions.</p></header><div className="flex gap-2">{(['queue', 'catalog', 'system'] as const).map(t => <Button key={t} variant={tab === t ? 'default' : 'outline'} onClick={() => setTab(t)}>{t === 'queue' ? 'Intake & inspection' : t === 'catalog' ? 'Card database' : 'System status'}</Button>)}</div>
  {submissionsError && <p role="alert" className="text-destructive">{submissionsError}</p>}
  {tab === 'queue' && <><div className="grid gap-3 sm:grid-cols-3">{['SUBMITTED', 'INSPECTING', 'GRADED'].map(status => <div key={status} className="glass rounded-xl p-4"><p className="text-xs text-muted-foreground">{status}</p><strong className="mt-2 block text-3xl">{submissions.filter(s => s.status === status).length}</strong></div>)}</div><section className="glass divide-y rounded-2xl p-5">{submissions.length === 0 && <p className="py-6 text-center text-muted-foreground">No grading requests yet.</p>}{submissions.map(s => <button key={s.id} className="flex min-h-20 w-full items-center gap-4 py-3 text-left" onClick={() => { setSelected(s.id); setNote(''); }}><img className="h-14 w-10 object-contain" src={s.cardArt} alt={s.cardName}/><span className="min-w-0 flex-1"><strong className="block text-sm">{s.cardName}</strong><span className="text-xs text-muted-foreground">{s.ownerName} · {s.cardSet}</span></span><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-primary">{s.status}</span></button>)}</section>
  {sub && <section className="glass space-y-4 rounded-2xl p-5"><h2 className="font-display text-xl font-bold">{sub.cardName} / intake record</h2><p className="break-all font-mono text-xs text-muted-foreground">{sub.id}</p><p className="text-sm">{sub.contactEmail}<br/>{sub.shippingName}<br/>{sub.shippingAddress}</p><p className="text-sm text-muted-foreground">Collector notes: {sub.notes || 'None'}</p>{sub.certSerial && <p className="break-all text-sm font-bold text-primary">{sub.finalGrade} · {sub.certSerial}</p>}<ol className="space-y-2 border-l-2 border-primary pl-4">{sub.events.map((e, i) => <li key={`${e.at}-${i}`} className="text-xs"><strong>{e.status}</strong> · {new Date(e.at).toLocaleString()}<p className="mt-1 text-muted-foreground">{e.note}</p></li>)}</ol>{nextStatus[sub.status] && <><label className="block text-sm font-semibold">{sub.status === 'GRADED' ? 'Shipping reference and handoff notes' : 'Inspection evidence / decision notes'}<textarea rows={3} className="vca-input mt-2 w-full" value={note} onChange={e => setNote(e.target.value)} placeholder="Document the physical inspection or verified shipping handoff. No emails are sent automatically."/></label>{sub.status === 'GRADING' && <label className="block text-sm">Professional grading decision<select className="vca-input ml-3" value={grade} onChange={e => setGrade(e.target.value as GradeLabel)}>{['VCA 8', 'VCA 9', 'VCA 10'].map(g => <option key={g}>{g}</option>)}</select></label>}<Button disabled={adminPending || (['INSPECTING', 'GRADING', 'GRADED'].includes(sub.status) && note.trim().length < 10)} onClick={() => { const promise = sub.status === 'GRADING' ? certifySubmission(sub.id, grade, note) : updateSubmissionStatus(sub.id, nextStatus[sub.status]!, note); void promise.then(() => { toast.success('Status recorded.'); setNote(''); }).catch(e => toast.error(e.message)); }}><ClipboardCheck className="mr-2 h-4 w-4"/>{sub.status === 'GRADING' ? 'Certify & issue serial' : `Mark ${nextStatus[sub.status]}`}</Button></>}</section>}
  {evidence.error && <p role="alert">{evidence.error.message}</p>}{sub && card && evidence.data && <PhotoInspection key={sub.id} card={card} evidence={evidence.data.inspection} onSave={async value => { await saveEvidence.mutateAsync(value); }} readOnly={!['RECEIVED', 'INSPECTING'].includes(sub.status)}/>}</>}
  {tab === 'catalog' && <section className="glass space-y-4 rounded-2xl p-5"><h2 className="flex gap-2 font-bold"><Database className="h-5 w-5"/>Bundled reference catalog</h2><p className="text-sm text-muted-foreground">Live scanning searches the external catalog. These {CATALOG.length} records are curated references, not live demand rankings.</p><input className="vca-input w-full" placeholder="Filter name or set" aria-label="Filter catalog" value={query} onChange={e => setQuery(e.target.value)}/>{CATALOG.filter(c => `${c.name} ${c.set}`.toLowerCase().includes(query.toLowerCase())).map(c => <Link className="flex items-center gap-3 border-b py-3 text-sm" key={c.id} to={`/card/${c.id}`}><img src={c.artUrl} alt="" className="h-12 w-9 object-contain"/><span><strong>{c.name}</strong><br/>{c.set} · {c.number}</span></Link>)}</section>}
  {tab === 'system' && <section className="glass space-y-4 rounded-2xl p-6"><h2 className="text-xl font-bold">Service boundaries</h2>{['Native email/password authentication is enabled.', 'Private workspace and submission policies are enforced by the database.', 'Certification and intake transitions run through restricted server operations.', 'Old shared demo tables are retained but quarantined from client access.', 'Unrestricted browser code execution is disabled.', 'Card prices depend on external catalog coverage, printing and source freshness.', 'Payment, shipping labels, email delivery, live marketplace and messaging integrations are not connected.'].map(text => <p key={text} className="border-b pb-3 text-sm text-muted-foreground">{text}</p>)}</section>}
  </div>;
}
