import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Gem, Layers, ScanLine, Microscope, PackageOpen, Plus } from 'lucide-react';
import { useVca } from '@/lib/store';
import { useLiveCollectionValue } from '@/lib/prices';
import { useAuth } from '@/lib/auth';
import { CATALOG } from '@/lib/data';
import { Button } from '@/components/ui/button';
import HoloSlab from '@/components/HoloSlab';
export default function Index() {
  const { currentUser, myItems, slabs, cardById, scanHistory, submissions } = useVca();
  const { session } = useAuth();
  const items = myItems(); const value = useLiveCollectionValue(items);
  const hero = items[0] ? cardById(items[0].cardId) ?? CATALOG[0] : CATALOG[0];
  return <div className="space-y-8"><section className="relative grid overflow-hidden rounded-[28px] border bg-white lg:grid-cols-[1.1fr_1fr]"><div className="relative z-10 flex flex-col justify-center p-6 sm:p-10"><p className="eyebrow">YOUR COLLECTION. A CLOSER LOOK.</p><h1 className="mt-5 font-display text-4xl font-extrabold leading-[1.05] tracking-[-.05em] text-blue-950 sm:text-5xl">Every card has<br/>a story.<br/><span className="text-red-600">Know yours.</span></h1><p className="mt-5 max-w-md text-sm leading-7 text-slate-500">{session ? `Welcome back, ${currentUser.displayName}. ` : ''}Identify your next find, explore its value and give it a display worth keeping.</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild className="min-h-12 rounded-xl bg-red-600 px-5 hover:bg-red-700"><Link to="/scanner"><ScanLine className="mr-2 h-4 w-4"/>Scan your card<ArrowUpRight className="ml-3 h-4 w-4"/></Link></Button><Button variant="outline" asChild className="min-h-12 rounded-xl"><Link to="/collection">Open collection</Link></Button></div><p className="mt-8 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.15em] text-slate-400"><span className="h-1.5 w-1.5 rounded-full bg-blue-600"/>Identify. Inspect. Display.</p></div><div className="relative bg-slate-50 p-4 sm:p-6"><div className="pointer-events-none absolute right-0 top-0 h-full w-2 bg-red-600"/><HoloSlab card={hero} grade={null} serial={null} config={{ labelStyle: 'classic', holo: 30, environment: 'studio', lightTint: '#244cb4', cardOffset: 0, showGrade: true, autoSpin: false }}/><p className="mt-3 text-center font-mono text-[9px] uppercase tracking-wider text-slate-400">{items.length ? 'Your latest card / ungraded display' : 'Sample display / not a graded specimen'}</p></div></section>
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{ label: 'Cards in collection', value: String(items.length), sub: 'Your private inventory' }, { label: 'Quoted raw subtotal', value: value.liveCount ? value.total.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }) : '—', sub: `${value.liveCount} / ${items.length} cards covered` }, { label: 'Digital displays', value: String(slabs.filter(s => s.kind === 'digital').length), sub: 'Ungraded visual keepsakes' }, { label: 'Grading requests', value: String(submissions.filter(s => s.userId === currentUser.id).length), sub: 'Track your intake records' }].map(stat => <div key={stat.label} className="glass rounded-2xl p-4 sm:p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{stat.label}</p><strong className="mt-3 block font-display text-3xl font-extrabold text-blue-950">{stat.value}</strong><p className="mt-2 text-[10px] text-slate-400">{stat.sub}</p></div>)}</section>
  <section><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-xl font-bold">The collector's toolkit</h2><span className="font-mono text-[10px] text-slate-400">BUILT FOR THE DETAILS</span></div><div className="grid gap-4 sm:grid-cols-3">{[{ title: 'Find the exact match', sub: 'Photo identification with set and printing confirmation.', icon: ScanLine, href: '/scanner', number: '01' }, { title: 'Inspect, not guess', sub: 'Your photos. Adjustable guides. Documented observations.', icon: Microscope, href: items[0] ? `/card/${encodeURIComponent(items[0].cardId)}` : '/scanner', number: '02' }, { title: 'Make it yours', sub: 'Studio lighting, holographic labels and dimensional displays.', icon: Gem, href: '/slab-creator', number: '03' }].map(tool => <Link key={tool.number} to={tool.href} className="group rounded-2xl border bg-white p-5 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-lg hover:shadow-blue-950/5"><div className="flex justify-between"><tool.icon className="h-6 w-6 text-blue-700"/><span className="font-mono text-xs text-slate-300">{tool.number}</span></div><h3 className="mt-6 font-display font-bold">{tool.title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{tool.sub}</p><ArrowRight className="mt-5 h-4 w-4 text-red-600 transition-transform group-hover:translate-x-1"/></Link>)}</div></section>
  <div className="grid gap-6 lg:grid-cols-[1.3fr_1fr]"><section className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-bold">Recently collected</h2><Link to="/collection" className="text-xs font-semibold text-primary">View all →</Link></div>{items.length ? <div className="mt-5 grid grid-cols-3 gap-3">{items.slice(0, 3).map(item => { const card = cardById(item.cardId); return card ? <Link key={item.id} to={`/card/${encodeURIComponent(card.id)}`}><img src={card.artUrl} alt={card.name} className="h-44 w-full rounded-lg object-contain"/><p className="mt-3 truncate text-xs font-bold">{card.name}</p><p className="mt-1 truncate text-[10px] text-slate-500">{card.set}</p></Link> : null; })}</div> : <div className="my-6 rounded-xl border border-dashed p-8 text-center"><Layers className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-4 text-sm font-semibold">A collection starts with one card.</p><p className="mt-2 text-xs text-slate-500">Scan your first card to bring this space to life.</p><Button variant="outline" asChild className="mt-4"><Link to="/scanner"><Plus className="mr-2 h-4 w-4"/>Add your first card</Link></Button></div>}</section><section className="glass rounded-2xl p-5"><h2 className="font-display text-lg font-bold">Your recent scans</h2>{scanHistory.length ? scanHistory.slice(0, 4).map(scan => <Link key={scan.id} to={scan.matchedCardId ? `/card/${encodeURIComponent(scan.matchedCardId)}` : '/scanner'} className="mt-4 flex items-center gap-3 border-b pb-4"><span className="rounded-lg bg-blue-50 p-2"><ScanLine className="h-4 w-4 text-blue-700"/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{scan.cardName}</p><p className="mt-1 text-[10px] text-slate-500">{scan.setName} · {scan.number}</p></div><ArrowUpRight className="h-4 w-4 text-slate-400"/></Link>) : <p className="py-8 text-sm leading-relaxed text-muted-foreground">Confirmed matches will appear here. No simulated scans or activity counts.</p>}<Link to="/submit" className="mt-6 flex items-center justify-between rounded-xl bg-slate-50 p-4 text-xs font-semibold"><span className="flex items-center gap-2"><PackageOpen className="h-4 w-4 text-red-600"/>Grading intake & progress</span><ArrowRight className="h-4 w-4"/></Link></section></div></div>;
}
