import { useEffect, useState } from 'react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { Bell, Compass, Gem, Home, Layers, Menu, MessageCircle, PackageOpen, ScanLine, ShieldCheck, Sparkles, Store, UserRound, X, ArrowUpRight, RefreshCw } from 'lucide-react';
import { useVca } from '@/lib/store';
import { useAuth } from '@/lib/auth';
import { Button } from './ui/button';
import VcaBrand from './VcaBrand';
import { cn } from '@/lib/utils';
const nav = [{ to: '/home', label: 'Overview', icon: Home }, { to: '/scanner', label: 'Card scanner', icon: ScanLine }, { to: '/collection', label: 'My collection', icon: Layers }, { to: '/slab-creator', label: 'Slab Studio', icon: Gem }, { to: '/submit', label: 'Grading requests', icon: PackageOpen }, { to: '/set-index', label: 'Set library', icon: Compass }, { to: '/slabook', label: 'Slabook', icon: Sparkles }, { to: '/discover', label: 'Discover', icon: Compass }, { to: '/marketplace', label: 'Marketplace', icon: Store }, { to: '/messenger', label: 'Messages', icon: MessageCircle }, { to: '/profile', label: 'Collector profile', icon: UserRound }];
export default function AppShell() {
  const { currentUser, saveError, saving, retrySave, notifications, markNotificationsRead, workspaceReady } = useVca();
  const { session, isAdmin, recovery } = useAuth();
  const location = useLocation();
  const [menu, setMenu] = useState<boolean>(false);
  const [notices, setNotices] = useState<boolean>(false);
  useEffect(() => { setMenu(false); setNotices(false); window.scrollTo({ top: 0 }); }, [location.pathname]);
  const legacy = ['/collection', '/submit', '/slabook', '/discover', '/set-index', '/marketplace', '/messenger', '/profile', '/collector/', '/card/'].some(p => location.pathname.startsWith(p));
  const prototypes = ['/slabook', '/discover', '/marketplace', '/messenger'].includes(location.pathname);
  const links = <><p className="px-4 pb-2 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Collector workspace</p>{nav.map(({ to, label, icon: Icon }, i) => <div key={to}>{i === 6 && <p className="px-4 pb-2 pt-6 text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">Community & connections</p>}<NavLink to={to} className={({ isActive }) => cn('mb-1 flex min-h-11 items-center gap-3 rounded-xl px-4 text-[13px] font-semibold transition-colors', isActive ? 'bg-blue-50 text-blue-800' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-900')}><Icon className="h-[18px] w-[18px]"/>{label}</NavLink></div>)}{isAdmin && <NavLink to="/admin" className="flex min-h-11 items-center gap-3 rounded-xl px-4 text-sm font-semibold text-primary"><ShieldCheck className="h-4 w-4"/>Administration</NavLink>}</>;
  return <div className="min-h-screen"><aside className="fixed inset-y-0 left-0 z-40 hidden w-60 flex-col border-r bg-white lg:flex"><div className="border-b px-6 py-6"><VcaBrand/></div><nav className="flex-1 overflow-y-auto px-3 pb-4">{links}</nav><Link to="/account" className="m-4 flex items-center gap-3 rounded-xl border bg-slate-50 p-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 font-bold text-blue-800">{currentUser.displayName.slice(0, 1).toUpperCase()}</span><span className="min-w-0 flex-1"><strong className="block truncate text-xs">{session ? currentUser.displayName : 'Guest workspace'}</strong><span className="text-[10px] text-slate-500">{session ? 'Account & security' : 'Sign in to save your cards'}</span></span><ArrowUpRight className="h-4 w-4 text-slate-400"/></Link></aside>
  <div className="lg:pl-60"><header className="sticky top-0 z-30 flex min-h-[76px] items-center justify-between gap-3 border-b bg-white/95 px-4 backdrop-blur-xl sm:px-7"><div className="lg:hidden"><VcaBrand/></div><p className="hidden font-mono text-[10px] font-semibold uppercase tracking-[.2em] text-slate-500 lg:block">The collector's point of view<span className="ml-4 text-red-600">/ VCA</span></p><div className="flex items-center gap-2"><span role="status" className="hidden text-xs text-slate-500 sm:block">{saveError ? 'Unsaved changes' : saving ? 'Saving…' : !session ? 'Guest session' : !workspaceReady ? 'Loading…' : 'Private workspace'}</span><button aria-label="Notifications" className="flex h-11 w-11 items-center justify-center rounded-full border bg-white" onClick={() => { setNotices(!notices); markNotificationsRead(); }}><Bell className="h-4 w-4"/></button><Button asChild className="hidden sm:inline-flex"><Link to="/scanner"><ScanLine className="mr-2 h-4 w-4"/>Scan a card</Link></Button><button className="flex h-11 w-11 items-center justify-center rounded-full border lg:hidden" aria-label="Open all pages" onClick={() => setMenu(true)}><Menu className="h-5 w-5"/></button></div></header>
  {menu && <div className="fixed inset-0 z-50 bg-slate-950/30 lg:hidden"><div role="dialog" aria-modal="true" aria-label="Navigation" className="ml-auto flex h-full w-80 max-w-full flex-col overflow-y-auto bg-white p-4"><div className="flex items-center justify-between"><VcaBrand/><Button variant="ghost" size="icon" onClick={() => setMenu(false)} aria-label="Close navigation"><X/></Button></div><nav>{links}<Link to="/account" className="mt-4 block rounded-xl bg-blue-50 p-4 font-bold text-primary">Account / Sign in</Link></nav></div></div>}
  {notices && <div className="fixed right-4 top-20 z-40 max-h-96 w-80 max-w-[calc(100vw-32px)] overflow-y-auto rounded-2xl border bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><strong>Notifications</strong><button className="min-h-11" onClick={() => setNotices(false)} aria-label="Close notifications"><X className="h-4 w-4"/></button></div>{notifications.length ? notifications.map(n => <p key={n.id} className="border-t py-3 text-sm">{n.text}</p>) : <p className="mt-4 text-sm text-muted-foreground">You're all caught up.</p>}</div>}
  <main className="mx-auto max-w-7xl px-4 pb-28 pt-6 sm:px-7 sm:pt-8 lg:pb-12"><div className="mb-5 flex flex-wrap items-center gap-2 text-xs text-slate-400"><span>WORKSPACE</span><span>/</span><span className="font-semibold uppercase tracking-wide text-slate-600">{nav.find(n => n.to === location.pathname)?.label ?? 'Card authority'}</span></div>
  {saveError && <div role="alert" className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><span>{saveError}</span><Button variant="outline" disabled={saving} onClick={retrySave}><RefreshCw className="mr-2 h-4 w-4"/>Retry save / load</Button></div>}
  {recovery && location.pathname !== '/account' && <Link to="/account" className="mb-4 block rounded-xl bg-blue-50 p-4 text-sm font-bold text-primary">Finish resetting your password →</Link>}
  {prototypes && <p className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-relaxed text-amber-900">Community preview. Example profiles/posts are labeled demo content; live public posting, messaging and marketplace synchronization are not connected. Your saved collector workspace remains private.</p>}
  {!session && <p className="mb-5 text-xs text-muted-foreground">Browsing as a guest. Changes stay in this tab only. <Link className="font-semibold text-primary underline" to="/account">Sign in before saving important work.</Link></p>}
  <div className={legacy ? 'legacy-ui' : ''}>{workspaceReady || location.pathname === '/account' ? <Outlet/> : <div className="glass rounded-2xl p-8 text-center text-sm text-muted-foreground">{saveError ? 'Your workspace could not be loaded. Retry above, or open Account to sign out.' : 'Loading your saved cards and photos…'}</div>}</div><footer className="mt-12 flex flex-wrap justify-between gap-2 border-t pt-5 text-[10px] font-semibold uppercase tracking-wider text-slate-400"><span>Verified Card Authority</span><span>Built for the details.</span></footer></main>
  <nav className="safe-bottom fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t bg-white/95 px-2 backdrop-blur-xl lg:hidden">{[{ to: '/home', icon: Home, label: 'Home' }, { to: '/collection', icon: Layers, label: 'Cards' }, { to: '/scanner', icon: ScanLine, label: 'Scan' }, { to: '/slab-creator', icon: Gem, label: 'Studio' }, { to: '/account', icon: UserRound, label: 'Account' }].map(({ to, icon: Icon, label }) => <NavLink key={to} to={to} className={({ isActive }) => cn('flex min-h-16 flex-col items-center justify-center gap-1 text-[10px] font-semibold', isActive ? 'text-blue-700' : 'text-slate-500')}><Icon className="h-5 w-5"/>{label}</NavLink>)}</nav></div></div>;
}
