import { useRef, useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Microscope, Move, Pin, RotateCcw, Save, Upload } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { downscaleForUpload, fileToDataUrl } from '@/lib/vision';
import { useVca, type InspectionNote } from '@/lib/store';
import type { CatalogCard } from '@/lib/types';
const initial: InspectionNote = { notes: '', pins: [], checks: [], guides: { left: 5, right: 95, top: 5, bottom: 95 } };
export default function PhotoInspection({ card, evidence, onSave, readOnly = false }: { card: CatalogCard; evidence?: InspectionNote; onSave?: (note: InspectionNote) => Promise<void>; readOnly?: boolean }) {
  const { inspections, saveInspection, backendReady } = useVca();
  const [note, setNote] = useState<InspectionNote>(evidence ?? inspections[card.id] ?? initial);
  const [side, setSide] = useState<'front' | 'back'>('front');
  const [zoom, setZoom] = useState<number>(1);
  const [brightness, setBrightness] = useState<number>(100);
  const [contrast, setContrast] = useState<number>(100);
  const [pan, setPan] = useState<{ x: number; y: number }>({ x: 0, y: 0 });
  const [mode, setMode] = useState<'pan' | 'pin'>('pan');
  const [label, setLabel] = useState<string>('Visible concern');
  const [guides, setGuides] = useState<boolean>(false);
  const drag = useRef<{ x: number; y: number } | null>(null);
  const photo = note[side];
  const save = useMutation({ mutationFn: async () => { if (onSave) await onSave(note); else await saveInspection(card.id, note); }, onSuccess: () => toast.success(backendReady || onSave ? 'Inspection notes saved.' : 'Notes kept in this session. Sign in for cloud saves.'), onError: e => toast.error(e.message) });
  const upload = useMutation({ mutationFn: async (file: File) => { if (file.size > 25000000 || !file.type.startsWith('image/')) throw new Error('Choose a photo under 25 MB.'); const url = await downscaleForUpload(await fileToDataUrl(file)); setNote(n => ({ ...n, [side]: url, pins: n.pins.filter(p => p.side !== side) })); setZoom(1); setPan({ x: 0, y: 0 }); }, onError: () => toast.error('Could not open this photo. Choose a JPEG or PNG.') });
  const ratio = (first: number, second: number): string => `${Math.round(first / (first + second) * 100)}:${Math.round(second / (first + second) * 100)}`;
  return <section className="glass space-y-5 rounded-3xl p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">PHOTO INSPECTION / MANUAL EVIDENCE</p><h2 className="mt-2 flex items-center gap-2 font-display text-2xl font-bold"><Microscope className="h-6 w-6 text-primary"/>Look closer.</h2></div>{!readOnly && <Button disabled={save.isPending} onClick={() => save.mutate()}><Save className="mr-2 h-4 w-4"/>{save.isPending ? 'Saving…' : 'Save notes'}</Button>}</div>
  <p className="text-xs leading-relaxed text-muted-foreground">Inspect your own photos, not a simulated specimen. Adjustments only change visibility. These tools cannot detect hidden layers, measure physical thickness or certify authenticity.</p>
  <div className="flex flex-wrap gap-2">{(['front', 'back'] as const).map(s => <Button key={s} variant={side === s ? 'default' : 'outline'} onClick={() => { setSide(s); setPan({ x: 0, y: 0 }); setZoom(1); }}>{s === 'front' ? 'Front photo' : 'Back photo'}</Button>)}{!readOnly && <label className="vca-upload"><Upload className="h-4 w-4"/>Upload {side}<input className="sr-only" type="file" accept="image/*" onChange={e => { if (e.target.files?.[0]) upload.mutate(e.target.files[0]); e.target.value = ''; }}/></label>}<Button variant="outline" onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); setBrightness(100); setContrast(100); }}><RotateCcw className="mr-2 h-4 w-4"/>Reset view</Button></div>
  <div className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="space-y-3"><div className="relative flex h-[420px] touch-none items-center justify-center overflow-hidden rounded-2xl border bg-slate-100" onPointerDown={e => { if (mode === 'pan') { drag.current = { x: e.clientX, y: e.clientY }; e.currentTarget.setPointerCapture(e.pointerId); } }} onPointerMove={e => { if (drag.current) { const dx = e.clientX - drag.current.x; const dy = e.clientY - drag.current.y; drag.current = { x: e.clientX, y: e.clientY }; setPan(p => ({ x: p.x + dx, y: p.y + dy })); } }} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}>
  {photo ? <div className="relative w-fit max-w-full" style={{ transform: `translate(${pan.x}px,${pan.y}px) scale(${zoom})` }} onClick={e => { if (mode !== 'pin' || readOnly) return; const r = e.currentTarget.getBoundingClientRect(); setNote(n => ({ ...n, pins: [...n.pins, { id: crypto.randomUUID(), side, label: label.trim() || 'Visible concern', x: Math.max(0, Math.min(100, (e.clientX - r.left) / r.width * 100)), y: Math.max(0, Math.min(100, (e.clientY - r.top) / r.height * 100)) }] })); }}><img src={photo} alt={`Your ${side} photo`} draggable={false} className="max-h-[390px] max-w-full object-contain" style={{ filter: `brightness(${brightness}%) contrast(${contrast}%)` }}/>{guides && <div className="pointer-events-none absolute border border-blue-600" style={{ left: `${note.guides.left}%`, right: `${100 - note.guides.right}%`, top: `${note.guides.top}%`, bottom: `${100 - note.guides.bottom}%` }}/ >}{note.pins.filter(p => p.side === side).map((p, i) => <span key={p.id} title={p.label} className="pointer-events-none absolute flex h-5 w-5 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-red-600 text-[10px] font-bold text-primary-foreground" style={{ left: `${p.x}%`, top: `${p.y}%` }}>{i + 1}</span>)}</div> : <div className="p-8 text-center"><Upload className="mx-auto h-9 w-9 text-muted-foreground"/><p className="mt-4 text-sm">No {side} photo attached.</p><p className="mt-2 text-xs text-muted-foreground">Upload the physical card to begin. No automatic grade is assigned.</p></div>}</div>
  <div className="grid grid-cols-3 gap-3">{[{ name: 'Zoom', value: zoom, min: 1, max: 4, step: .1, set: setZoom }, { name: 'Brightness', value: brightness, min: 50, max: 180, step: 1, set: setBrightness }, { name: 'Contrast', value: contrast, min: 50, max: 180, step: 1, set: setContrast }].map(c => <label key={c.name} className="text-xs text-muted-foreground">{c.name}<input className="mt-2 w-full accent-blue-700" type="range" min={c.min} max={c.max} step={c.step} value={c.value} onChange={e => c.set(Number(e.target.value))}/></label>)}</div><div className="flex gap-2"><Button variant={mode === 'pan' ? 'default' : 'outline'} onClick={() => setMode('pan')}><Move className="mr-2 h-4 w-4"/>Pan</Button>{!readOnly && <Button variant={mode === 'pin' ? 'default' : 'outline'} onClick={() => setMode('pin')}><Pin className="mr-2 h-4 w-4"/>Mark concern</Button>}<Button variant="outline" onClick={() => setGuides(g => !g)}>Border guides</Button></div>{mode === 'pin' && !readOnly && <Input aria-label="Concern label" value={label} onChange={e => setLabel(e.target.value)} placeholder="Describe concern, then click photo"/>}
  {guides && <div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">First crop the image tightly to the card edges. Position guides at the printed inner border. Ratios are manual estimates, affected by perspective.</p><div className="mt-3 grid grid-cols-2 gap-3">{(['left', 'right', 'top', 'bottom'] as const).map(k => <label key={k} className="text-xs capitalize">{k}<input aria-label={`${k} border guide`} type="range" className="w-full accent-blue-700" min={k === 'left' || k === 'top' ? 1 : 70} max={k === 'left' || k === 'top' ? 30 : 99} value={note.guides[k]} onChange={e => setNote(n => ({ ...n, guides: { ...n.guides, [k]: Number(e.target.value) } }))}/></label>)}</div><p className="mt-2 text-xs font-bold">Manual L:R {ratio(note.guides.left, 100 - note.guides.right)} · T:B {ratio(note.guides.top, 100 - note.guides.bottom)}</p></div>}</div>
  <div className="space-y-4"><div className="rounded-2xl border p-4"><p className="text-xs font-bold uppercase tracking-wider">Catalog reference / not your specimen</p><img src={card.artUrl} alt="Catalog reference" className="mx-auto mt-3 h-48 max-w-full object-contain"/></div><div className="space-y-2">{['Corners reviewed', 'Edges reviewed', 'Surface reviewed', 'Print text compared', 'Back reviewed'].map(check => <label key={check} className="flex min-h-9 items-center gap-3 text-sm"><input type="checkbox" disabled={readOnly} checked={note.checks.includes(check)} onChange={e => setNote(n => ({ ...n, checks: e.target.checked ? [...n.checks, check] : n.checks.filter(c => c !== check) }))}/>{check}</label>)}</div><label className="block text-sm font-medium">Inspection notes<textarea value={note.notes} disabled={readOnly} onChange={e => setNote(n => ({ ...n, notes: e.target.value }))} rows={5} className="vca-input mt-2 w-full resize-y" placeholder="Describe visible wear and uncertainty. These are your observations, not a certified grade."/></label><div className="space-y-2">{note.pins.map(p => <div className="flex items-center gap-2 rounded-lg bg-red-50 px-3 py-2 text-xs" key={p.id}><Pin className="h-3 w-3 shrink-0 text-red-600"/><span className="flex-1">{p.side}: {p.label}</span>{!readOnly && <button className="min-h-8 text-red-700 underline" onClick={() => setNote(n => ({ ...n, pins: n.pins.filter(pin => pin.id !== p.id) }))}>Remove</button>}</div>)}</div></div></div></section>;
}
